import yaml
with open(workflow.source_path("config.yaml")) as cfg:
    default_config = yaml.load(cfg, yaml.Loader)
default_config.update(config)
config = default_config

sample_ids = list(config['aligned_files'].keys())
paired_end_flag = "" if config['paired_end'] else '-se'

def sample_to_bam(sample_id):
    return config['aligned_files'][sample_id]

rule all:
    input:
        "results/precheck.txt",
        "results/check_samformat.txt",
        expand("results/STATS/total_num_reads.txt", sample_id = sample_ids)

rule precheck:
    input:
        aligned = config['aligned_files'].values(),
        cfg = config['port_config'],
    output:
        "results/precheck.txt"
    params:
        script = workflow.source_path("scripts/run_normalization")
    shell:
        "perl {params.script} --aligned_files {input.aligned} --cfg {input.cfg}"

rule get_total_num_reads:
    input:
        bam = lambda wildcards: sample_to_bam[wildcards.sample_id] 
    output:
        "results/{sample_id}/total_num_reads.txt"
    container:
        config['containers']['samtools']
    shell:
        "samtools view -c -F 2432 {input.bam} > {output}"

rule get_total_num_reads_agg:
    input:
        tnr = expand("results/{sample_id}/total_num_reads.txt", sample_id = sample_ids)
    output:
        tnr = "results/STATS/total_num_reads.txt"
    run:
        with open(output.tnr, 'wt') as out:
            for sample_id, tnrf in zip(sample_ids, input.tnr):
                tot_num_reads = open(tnrf).read()
                out.write("{sample_id}\t{tot_num_reads}")

rule check_samformat:
    input:
        [sample_to_bam(sample_id) for sample_id in sample_ids]
    output:
        "results/check_samformat.txt"
    params:
        pe = paired_end_flag,
        script = workflow.source_path("scripts/check_samformat.pl")
    container:
        config['containers']['samtools']
    shell:
        "perl {params.script} {input} {params.pe}"
