import yaml
with open(workflow.source_path("config.yaml")) as cfg:
    default_config = yaml.load(cfg, yaml.Loader)

def update_recursive(A, B):
    ''' like A.update(B) but performs in-place deep updates of all subdicts too '''
    for key, val in B.items():
        if key not in A:
            A[key] = val
        else:
            if isinstance(A[key], dict) and isinstance(B[key], dict):
                update_recursive(A[key], B[key])
            else:
                A[key] = val
update_recurisve(default_config,config)
config = default_config

def sample_to_bam(sample_id):
    return config['aligned_files'][sample_id]

def read_port_config(cfg_file):
    config = dict()
    with open(cfg_file, "rt") as cfg_file:
        for line in cfg_file:
            line = line.strip()
            if line.startswith("#"):
                continue
            elif len(line) == 0:
                continue
            else:
                splits = line.split(" = ")
                if len(splits) == 1:
                    before = splits[0]
                    config[before] = None
                else:
                    before, after = splits
                    config[before] = after
    return config
port_config = read_port_config(config['port_config'])

sample_ids = list(config['aligned_files'].keys())
paired_end_flag = "" if config['paired_end'] else '-se'
orientation_flag = '' if not port_config['STRANDED'] else "-str_f" if port_config['FWD'] == "TRUE" else "-str_r"
stranded_flag = '-stranded' if port_config['STRANDED'] == "TRUE" else '',
sense_types = [".sense", ".antisense"] if port_config['STRANDED'] == "TRUE" else [""]

# TODO: allow this to be configured by the user --cutoff_highexp
# and separetly for part1 and part2, possibly
cutoff_highexp = 3 # percent

wildcard_constraints:
    suffix = "[^\.]+",
    u_nu = "u|nu",
    unique_nu = "Unique|NU",

rule all:
    input:
        "results/precheck.pass",
        "results/check_samformat.pass",
        "results/STATS/total_num_reads.txt",
        "results/STATS/mappingstats_summary.txt",
        "results/one-line.fa",
        expand("results/READS/{sample_id}/GNORM/Unique/{sample_id}.filtered_u.sam.gz", sample_id = sample_ids),
        "results/STATS/percent_reads_chr_gene.txt",
        "results/READS/master_list_of_genes.txt",
        expand("results/READS/{sample_id}/GNORM/Unique/{sample_id}.filtered_u.genefilter.sense.txt.gz", sample_id = sample_ids),
        expand("results/READS/{sample_id}/GNORM/NU/{sample_id}.filtered_nu.genefilter.sense.txt.gz", sample_id = sample_ids),
        #expand("results/READS/{sample_id}/GNORM/Unique/{sample_id}.filtered_u.genes{type}.sam.gz", sample_id = sample_ids, type = sense_types),
        #expand("results/READS/{sample_id}/GNORM/NU/{sample_id}.filtered_nu.genes{type}.sam.gz", sample_id = sample_ids, type = sense_types),
        expand("results/STATS/lineCounts/gene.unique{type}.lc.txt", type = sense_types),
        expand("results/STATS/lineCounts/gene.nu{type}.lc.txt", type = sense_types),
        "results/STATS/GENE/sense_vs_antisense_genemappers_NU.txt",
        expand("results/READS/{sample_id}/GNORM/Unique/{sample_id}.filtered_u.genefilter{type}.genequants", sample_id = sample_ids, type = sense_types),
        expand("results/READS/{sample_id}/GNORM/NU/{sample_id}.filtered_nu.genefilter{type}.genequants", sample_id = sample_ids, type = sense_types),
        expand("results/STATS/GENE/percent_genemappers_{unique_nu}_{sense}.txt", unique_nu = ["Unique", "NU"], sense=["sense", "antisense"]),
        expand("results/READS/{sample_id}/{sample_id}.genepercents{type}.txt", sample_id = sample_ids, type = sense_types),
        expand("results/READS/{sample_id}/{sample_id}.genepercents.nu{type}.txt", sample_id = sample_ids, type = sense_types),
        expand("results/STATS/GENE/percent_high_expresser_gene{type}.txt", type=sense_types),
        "results/STATS/GENE/expected_num_reads_gnorm.txt",

rule precheck:
    input:
        aligned = config['aligned_files'].values(),
        cfg = config['port_config'],
    output:
        touch("results/precheck.pass")
    container:
        config['containers']['samtools']
    shell:
        "perl /workflow/scripts/run_normalization --aligned_files {input.aligned} --cfg {input.cfg}"

rule sample_ids:
    output:
        "results/sample_ids.txt"
    run:
        with open(output[0], 'wt') as f:
            for sample_id in sample_ids:
                f.write(f"{sample_id}\n")

rule get_total_num_reads:
    input:
        bam = lambda wildcards: sample_to_bam(wildcards.sample_id) 
    output:
        "results/SAMPLES/{sample_id}/total_num_reads.txt"
    container:
        config['containers']['samtools']
    shell:
        "samtools view -c -F 2432 {input.bam} > {output}"

rule get_total_num_reads_agg:
    input:
        tnr = expand("results/SAMPLES/{sample_id}/total_num_reads.txt", sample_id = sample_ids)
    output:
        tnr = "results/STATS/total_num_reads.txt"
    run:
        with open(output.tnr, 'wt') as out:
            for sample_id, tnrf in zip(sample_ids, input.tnr):
                tot_num_reads = open(tnrf).read()
                out.write(f"{sample_id}\t{tot_num_reads}")

rule check_samformat:
    input:
        [sample_to_bam(sample_id) for sample_id in sample_ids]
    output:
        touch("results/check_samformat.pass")
    params:
        pe = paired_end_flag,
    container:
        config['containers']['samtools']
    shell:
        "perl /workflow/scripts/check_samformat.pl {input} {params.pe}"

rule sam2mappingstats:
    input:
        bam = lambda wildcards: sample_to_bam(wildcards.sample_id),
        tnr = "results/SAMPLES/{sample_id}/total_num_reads.txt",
    output:
        "results/SAMPLES/{sample_id}/{sample_id}_mappingstats.txt"
    container:
        config['containers']['samtools']
    shell:
        "perl /workflow/scripts/sam2mappingstats.pl {input.bam} {output} -numreads `cat {input.tnr}`"

rule getstats:
    input:
        expand("results/SAMPLES/{sample_id}/{sample_id}_mappingstats.txt", sample_id=sample_ids),
    output:
        mappingstats = "results/STATS/mappingstats_summary.txt",
        mito = "results/STATS/mitochondrial_percents.txt",
    params:
        mito = port_config['CHRM']
    container:
        config['containers']['perl']
    shell:
        "perl /workflow/scripts/getstats.pl {input} -mito_file {output.mito} -summary_file {output.mappingstats} -mito {params.mito}"

rule modify_to_onelinefa:
    input:
        fa = port_config['GENOME_FA'],
    output:
        fa = "results/one-line.fa"
        #TODO: make this temporary?
    container:
        #TODO: we need a better way to handle this container
        config['containers']['perl']
    shell:
        'perl /workflow/scripts/rum-2.0.5_05/bin/modify_fa_to_have_seq_on_one_line.pl {input.fa} > {output.fa};'

rule filtersam_gnorm:
    input:
        bam = lambda wildcards: sample_to_bam(wildcards.sample_id),
    output:
        unique = "results/READS/{sample_id}/GNORM/Unique/{sample_id}.filtered_u.sam.gz",
        NU = "results/READS/{sample_id}/GNORM/NU/{sample_id}.filtered_nu.sam.gz",
    params:
        paired_end = paired_end_flag,
        mito = port_config['CHRM']
    container:
        config['containers']['samtools']
    shell:
        # TODO: should -u/-nu ever be set? Appears to happen in PORT 0.8.5 if there are no NU mappers at all
        "perl /workflow/scripts/filter_sam_gnorm.pl {input} {output} {params.paired_end} -mito {params.mito}"

rule get_percent_numchr:
    input:
        "results/READS/{sample_id}/{norm_type}/Unique/{sample_id}.filtered_u.sam.gz"
    output:
        "results/READS/{sample_id}/{norm_type}/Unique/{sample_id}.filtered_u.numchr_count.txt"
    container:
        config['containers']['perl']
    shell:
        "perl /workflow/scripts/get_percent_numchr.pl {input} {output}"

rule get_chr_stats_gnorm:
    input:
        expand("results/READS/{sample_id}/GNORM/Unique/{sample_id}.filtered_u.numchr_count.txt", sample_id = sample_ids),
    output:
        "results/STATS/percent_reads_chr_gene.txt"
    container:
        config['containers']['perl']
    shell:
        "perl /workflow/scripts/get_chr_stats.pl {output} {input}"

rule get_readlength:
    input:
        bam = [sample_to_bam(sample_id) for sample_id in sample_ids],
    output:
        "results/READS/readlength.txt"
    container:
        config['containers']['samtools']
    shell:
        "perl /workflow/scripts/get_readlength.pl {input} > {output}"

rule get_master_list_of_genes:
    input:
        ens = port_config['GENE_INFO_FILE'],
        readlength = "results/READS/readlength.txt",
    output:
        "results/READS/master_list_of_genes.txt"
    container:
        config['containers']['perl']
    params:
        stranded = stranded_flag,
    shell:
        "perl /workflow/scripts/get_master_list_of_genes.pl {input.ens} {output} {params.stranded} -readlength `cat {input.readlength}`"

rule sam2genes_gnorm_split:
    input:
        bam = lambda wildcards: sample_to_bam(wildcards.sample_id)
    output:
        dir = temp(directory("results/READS/{sample_id}/GNORM/{unique_nu}/sam2genes_splits/")),
    container:
        config['containers']['samtools']
    params:
        n_rows_per_batch = 5_000_000
    shell:
        # Perform the splits and write out the split suffixes
        "mkdir {output.dir} && samtools view {input.bam} | split -l {params.n_rows_per_batch} - {output.dir}/sam2genes_temp."

checkpoint sam2genes_gnorm_split_suffixes:
    # NOTE: snakemake doesn't support temporary output files in checkpoints, so we make this rule a checkpoint
    # instead of sam2genes_gnorm_split, and this rule just summarizes the files of sam2genes_gnorm_split
    input:
        dir = "results/READS/{sample_id}/GNORM/{unique_nu}/sam2genes_splits/",
    output:
        suffixes = "results/READS/{sample_id}/GNORM/{unique_nu}/sam2genes_splits.txt",
    container:
        config['containers']['perl']
    shell:
        "find {input.dir}/* | sed -nE \"s/.*sam2genes_temp.(.*)/\\1/p\" > {output.suffixes}"

rule sam2genes_gnorm:
    input:
        suffixes = "results/READS/{sample_id}/GNORM/{unique_nu}/sam2genes_splits.txt",
        dir = "results/READS/{sample_id}/GNORM/{unique_nu}/sam2genes_splits/",
        ens = port_config['GENE_INFO_FILE'],
    output:
        temp("results/READS/{sample_id}/GNORM/{unique_nu}/sam2genes/sam2genes_temp.{suffix}.txt.gz")
    params:
        paired_end = paired_end_flag,
        orientation = orientation_flag,
    container:
        config['containers']['samtools']
    shell:
        "perl /workflow/scripts/sam2genes.pl {input.dir}/sam2genes_temp.{wildcards.suffix} {input.ens} {output} {params.paired_end} {params.orientation}"

def all_sam2genes_output(wildcards):
        out = list(checkpoints.sam2genes_gnorm_split_suffixes.get(sample_id = wildcards.sample_id, unique_nu = wildcards.unique_nu).output)
        with out[0].open() as f:
            suffixes = f.read().splitlines()
        return [f"results/READS/{wildcards.sample_id}/GNORM/{wildcards.unique_nu}/sam2genes/sam2genes_temp.{suffix}.txt.gz"
                for suffix in suffixes]

rule cat_genes_files:
    input:
        all_sam2genes_output
    output:
        "results/READS/{sample_id}/GNORM/{unique_nu}/{sample_id}.filtered_{u_nu}.txt.gz",
    container:
        config['containers']['perl']
    shell:
        "zcat {input} | gzip > {output}"

rule genefilter:
    input:
        sam = "results/READS/{sample_id}/GNORM/{unique_nu}/{sample_id}.filtered_{u_nu}.sam.gz",
        genefile = "results/READS/{sample_id}/GNORM/{unique_nu}/{sample_id}.filtered_{u_nu}.txt.gz",
    output:
        expand("results/READS/{{sample_id}}/GNORM/{{unique_nu}}/{{sample_id}}.filtered_{{u_nu}}.genefilter{type}.txt.gz", type=sense_types),
        expand("results/READS/{{sample_id}}/GNORM/{{unique_nu}}/{{sample_id}}.filtered_{{u_nu}}.genes{type}.linecount.txt", type=sense_types),
    params:
        stranded = stranded_flag,
        paired = paired_end_flag,
        outname = "results/READS/{sample_id}/GNORM/{unique_nu}/{sample_id}.filtered_{u_nu}.genes.sam.gz",
    container:
        config['containers']['samtools']
    shell:
        "perl /workflow/scripts/genefilter.pl {input.sam} {input.genefile} {params.outname} {params.paired} {params.stranded}"

rule copy_lcfiles:
    input:
        expand("results/READS/{sample_id}/GNORM/Unique/{sample_id}.filtered_u.genes{type}.linecount.txt", type=sense_types, sample_id = sample_ids),
        expand("results/READS/{sample_id}/GNORM/NU/{sample_id}.filtered_nu.genes{type}.linecount.txt", type=sense_types, sample_id = sample_ids),
    output:
        expand("results/STATS/lineCounts/gene.unique{type}.lc.txt", type = sense_types),
        expand("results/STATS/lineCounts/gene.nu{type}.lc.txt", type = sense_types),
    params:
        out_dir = "results/STATS/lineCounts/",
        input_dirs = expand("results/READS/{sample_id}/", sample_id = sample_ids),
        stranded = stranded_flag,
    container:
        config['containers']['perl']
    shell:
        "perl /workflow/scripts/copy_lcfiles.pl {params.out_dir} {params.input_dirs} {params.stranded} -gnorm"

rule get_sense2antisense_stats:
    input:
        expand("results/READS/{sample_id}/GNORM/Unique/{sample_id}.filtered_u.genes{type}.linecount.txt", type=sense_types, sample_id = sample_ids),
        expand("results/READS/{sample_id}/GNORM/NU/{sample_id}.filtered_nu.genes{type}.linecount.txt", type=sense_types, sample_id = sample_ids),
        sample_file = "results/sample_ids.txt",
    output:
        "results/STATS/GENE/sense_vs_antisense_genemappers_Unique.txt",
        "results/STATS/GENE/sense_vs_antisense_genemappers_NU.txt",
    container:
        config['containers']['perl']
    shell:
        "perl /workflow/scripts/get_sense2antisense_stats.pl {input.sample_file} results/READS -gnorm"

rule quantify_genes_gnorm:
    input:
        # TODO: does this support non-stranded files? those don't have ".sense"
        genefilter = "results/READS/{sample_id}/GNORM/{unique_nu}/{sample_id}.filtered_{u_nu}.genefilter.sense.txt.gz",
        ens = "results/READS/master_list_of_genes.txt"
    output:
        "results/READS/{sample_id}/GNORM/{unique_nu}/{sample_id}.filtered_{u_nu}.genefilter{type}.genequants",
    params:
        paired = paired_end_flag,
    container:
        config['containers']['perl']
    shell:
        "perl /workflow/scripts/quantify_genes.pl {input.genefilter} {input.ens} {output} {params.paired}"

rule get_percent_genemappers:
    input:
        expand("results/READS/{sample_id}/GNORM/Unique/{sample_id}.filtered_u.sam.gz", sample_id = sample_ids),
        expand("results/READS/{sample_id}/GNORM/NU/{sample_id}.filtered_nu.sam.gz", sample_id = sample_ids),
        expand("results/READS/{sample_id}/GNORM/Unique/{sample_id}.filtered_u.genes{type}.linecount.txt", type=sense_types, sample_id = sample_ids),
        expand("results/READS/{sample_id}/GNORM/NU/{sample_id}.filtered_nu.genes{type}.linecount.txt", type=sense_types, sample_id = sample_ids),
        sample_file = "results/sample_ids.txt"
    output:
        "results/STATS/GENE/percent_genemappers_NU_antisense.txt",
        "results/STATS/GENE/percent_genemappers_NU_sense.txt",
        "results/STATS/GENE/percent_genemappers_Unique_antisense.txt",
        "results/STATS/GENE/percent_genemappers_Unique_sense.txt",
    params:
        stranded = stranded_flag,
    container:
        config['containers']['perl']
    shell:
        "perl /workflow/scripts/get_percent_genemappers.pl {input.sample_file} results/READS {params.stranded}"

rule get_high_genes:
    input:
        expand("results/READS/{{sample_id}}/GNORM/Unique/{{sample_id}}.filtered_u.genefilter{type}.genequants", type = sense_types),
        expand("results/READS/{{sample_id}}/GNORM/Unique/{{sample_id}}.filtered_u.genefilter{type}.txt.gz", type = sense_types),
    output:
        expand("results/READS/{{sample_id}}/{{sample_id}}.genepercents{type}.txt", type = sense_types),
        expand("results/READS/{{sample_id}}/{{sample_id}}.high_expressers_gene{type}.txt", type = sense_types),
    params:
        paired = paired_end_flag,
        stranded = stranded_flag,
        outname = "results/READS/{sample_id}/{sample_id}.genepercents.txt",
        cutoff = cutoff_highexp,
    container:
        config['containers']['perl']
    shell:
        "perl /workflow/scripts/get_genepercents.pl results/READS/{wildcards.sample_id} {params.cutoff} {params.outname} {params.stranded} {params.paired}"

rule get_genepercents:
    # Same as get_high_genes but for non-unique and has a hard-coded cutoff of 100 (i.e., no cutoff)
    input:
        expand("results/READS/{{sample_id}}/GNORM/NU/{{sample_id}}.filtered_nu.genefilter{type}.genequants", type = sense_types),
        expand("results/READS/{{sample_id}}/GNORM/NU/{{sample_id}}.filtered_nu.genefilter{type}.txt.gz", type = sense_types),
    output:
        expand("results/READS/{{sample_id}}/{{sample_id}}.genepercents.nu{type}.txt", type = sense_types),
    params:
        paired = paired_end_flag,
        stranded = stranded_flag,
        cutoff = 100, # fixed, not parameterized
        outname = "results/READS/{sample_id}/{sample_id}.genepercents.nu.txt",
    container:
        config['containers']['perl']
    shell:
        "perl /workflow/scripts/get_genepercents.pl results/READS/{wildcards.sample_id} {params.cutoff} {params.outname} {params.stranded} {params.paired} -nu"

rule get_percent_high_expresser_gnorm:
    input:
        expand("results/READS/{sample_id}/{sample_id}.high_expressers_gene{type}.txt", sample_id = sample_ids, type = sense_types),
        sample_ids = "results/sample_ids.txt"
    output:
        expand("results/STATS/GENE/percent_high_expresser_gene{type}.txt", type=sense_types),
    params:
        stranded = stranded_flag,
    container:
        config['containers']['perl']
    shell:
        "perl /workflow/scripts/get_percent_high_expresser_gnorm.pl {input.sample_ids} results/READS {params.stranded}"

rule predict_num_reads_gnorm:
    #TODO: this script originally was modified by filter_highexp option, but I'm not sure it should be
    input:
        expand("results/READS/{sample_id}/GNORM/Unique/{sample_id}.filtered_u.genes{type}.linecount.txt", sample_id = sample_ids, type = sense_types),
        expand("results/READS/{sample_id}/GNORM/NU/{sample_id}.filtered_nu.genes{type}.linecount.txt", sample_id = sample_ids, type = sense_types),
        sample_ids = "results/sample_ids.txt"
    output:
        "results/STATS/GENE/expected_num_reads_gnorm.txt",
    params:
        stranded = stranded_flag,
        paired = paired_end_flag,
    container:
        config['containers']['perl']
    shell:
        "perl /workflow/scripts/predict_num_reads_gnorm.pl {input.sample_ids} results/READS {params.paired} {params.stranded}"
