#!/usr/bin/env perl
#use warnings;
#use strict;
use lib ("$Bin/pm/lib/perl5");
#use File::Type;

my $USAGE =  "\nUsage: run_normalization --aligned_files <aligned files> --cfg <cfg file> [options]

where:
--aligned_files <aligned files> : list of aligned (bam/sam) files
--cfg <cfg file> : is a cfg file for the study
";


for(my $i=0; $i<@ARGV; $i++) {
    if ($ARGV[$i] eq '-v'){
        die "\nPORT v0.8.5e-beta\n\n";
    }
}
for(my $i=0; $i<@ARGV; $i++) {
    if ($ARGV[0] eq '-h'){
        die $USAGE;
    }
}

if(@ARGV < 3) {
    die $USAGE;
}



my $required = 0;

my ($cfg_file);
my $part2 = "false";
my @aligned_files;
for(my $i=0; $i<@ARGV; $i++) {
    my $option_found = "false";
    if ($ARGV[$i] eq '--aligned_files'){
        $option_found = "true";
        $i++;
        while($i < @ARGV) {
            if ($ARGV[$i] =~ /^-/) {
                last
            }
            push(@aligned_files, $ARGV[$i]);
            $i++;
        }
        $required++;
    }
    if ($ARGV[$i] eq '--cfg'){
        $option_found = "true";
        $cfg_file = $ARGV[$i+1];
        if ($cfg_file =~ /^-/ | $cfg_file eq ""){
            die "\nplease provide <cfg file> for --cfg\n";
        }
        $i++;
        $required++;
    }
    if($option_found eq "false") {
        die "option \"$ARGV[$i]\" was not recognized.\n";
    }
}
if ($required ne '2'){
    die "please specify the required parameters: --cfg\n";
}
if (length(@aligned_files) == 0) {
    die "need to provide at least one aligned_file"
}

my $GNORM = "false";
my $EIJ = "false";
#check_config file
unless (-e $cfg_file){
    die "ERROR: cannot find file \"$cfg_file\". please provide a cfg file for the study\n";
}
my %Config;
&parse_config_file ($cfg_file, \%Config);

use Cwd 'abs_path';
my $norm_script_dir = abs_path($0);
$norm_script_dir =~ s/\/run_normalization//;

my $normcnt = 0;
if ($GENE_NORM =~ /true/i){
    $GNORM = "true";
    $normcnt++;
}
if ($EXON_INTRON_JUNCTION_NORM =~ /^true/i){
    $EIJ = "true";
    $normcnt++;
}

if ($normcnt == 0){
    die "ERROR: Please select a type of Normalization you'd like to use (# 0. NORMALIZTION and DATA TYPE - [A] Normalization Type in your cfg file \"$cfg_file\")\n\n";
}
my $geneinfo;
if ($EIJ eq "true"){
    $geneinfo = $GENE_INFO_FILE;
    unless (-e $geneinfo){
        die "ERROR: cannot find file \"$geneinfo\"\nYou need to provide a gene information file (# 2. GENE INFO in your cfg file \"$cfg_file\")\n\n";
    }
}
my $chromname = "false";
my $chrom = $CHRNAMES;
my %CNAMES;
unless ($chrom =~ /^$/){
    $chromname = "true";
    unless (-e $chrom){
        die "ERROR: cannot find file \"$chrom\"\nPlease double check [D-i] File of standard chromosome (# 0. NORMALIZTION and DATA TYPE in your cfg file \"$cfg_file\")\n\n";
    }
    open(NAMES, $chrom);
    while(my $line = <NAMES>){
        chomp($line);
        $CNAMES{$line}=1;
    }
    close(NAMES);
}

my $mito = $CHRM;
if ($mito =~ /^$/){
    die "ERROR: You need to provide [D-ii] Name of mitochondrial chromosome (# 0. NORMALIZTION and DATA TYPE in your cfg file \"$cfg_file\")\n\n";
}

my $genome = $GENOME_FA;
unless (-e $genome){
    die "ERROR: cannot find file \"$genome\"\nYou need to provide [1] genome sequence one-line fasta file (# 3. FA and FAI in your cfg file \"$cfg_file\")\n\n";
}
my $fai = $GENOME_FAI;
unless (-e $fai){
    die "ERROR: cannot find file \"$fai\"\nYou need to provide [2] index file (# 3. FA and FAI in your cfg file \"$cfg_file\")\n\n";
}

my $pref = "false";
if ($rRNA_PREFILTERED =~ /^true/i){
    $pref = "true";
}
my $rRNA = $rRNA_FA;
if ($pref eq "false"){
    unless (-e $rRNA){
        die "ERROR: cannot find file \"$rRNA\"\nYou need to provide [2] rRNA sequence fasta file (# 4. rRNA in your cfg file \"$cfg_file\")\n\n";
    }
}
my $ensGene;
if ($GNORM eq "true"){
    $ensGene = $GENE_INFO_FILE;
    unless (-e $ensGene){
        die "ERROR: cannot find file \"$ensGene\"\nYou need to provide a gene information file (# 2. GENE INFO in your cfg file \"$cfg_file\")\n\n";
    }
}

my $strand_info = "";
my $strand_info_sam2cov = "";
if ($STRANDED =~ /^true/i){
    $strand_info_sam2cov = "-str";
    my $strand_flag = 0;
    if ($FWD =~ /^true/i){
        $strand_flag++;
        $strand_info = "-str_f";
    }
    if ($REV =~ /^true/i){
        $strand_flag++;
        $strand_info = "-str_r";
    }
    if ($strand_flag ne "1"){
        die "Please specify the read orientation. (# 0. NORMALIZTION and DATA TYPE - [B] Stranded Data in your cfg file \"$cfg_file\")\n\n";
    }
}
my $sam2cov = "false";
my $sam2cov_loc;
if ($SAM2COV =~ /^true/i){
    $sam2cov = "true";
    my $num_cov = 0;
    unless (-e $SAM2COV_LOC){
        die "You need to provide sam2cov location. (# 5. DATA VISUALIZATION in your cfg file \"$cfg_file\")\n";
    }
    $sam2cov_loc = $SAM2COV_LOC;
    if ($RUM =~ /^true/i){
        $aligner = "-rum";
        $num_cov++;
    }
    if ($STAR_GSNAP =~ /^true/i){
        $aligner = "-star";
        $num_cov++;
    }
    if ($num_cov ne '1'){
        die "Please specify which aligner was used. (# 5. DATA VISUALIZATION in your cfg file \"$cfg_file\")\n\n";
    }
}
my $delete_int_sam = "true";
my $convert_sam2bam = "false";
my $gzip_cov = "false";
if ($DELETE_INT_SAM ne ""){
    if ($DELETE_INT_SAM =~ /^true/i){
        $delete_int_sam = "true";
    }
    if ($DELETE_INT_SAM=~ /^false/i){
        $delete_int_sam = "false";
    }
}
if ($CONVERT_SAM2BAM ne ""){
    if ($CONVERT_SAM2BAM =~ /^true/i){
        $convert_sam2bam = "true";
    }
    if ($CONVERT_SAM2BAM =~ /^false/i){
        $convert_sam2bam= "false";
    }
}
if ($GZIP_COV ne ""){
    if ($GZIP_COV =~ /^true/i){
        $gzip_cov = "true";
    }
    if ($GZIP_COV =~ /^false/i){
        $gzip_cov = "false";
    }
}

#check sam/bam
my $se = "false";
my $pe = "false";
my $se_option = "";
my $se_cnt = 0;

#check single/paired
for my $file_loc (@aligned_files) {
    my $flag = `samtools view $file_loc | head -1 | cut -f 2`;
    if ($flag & 1) {
        $pe = "true";
    } else {
        $se = "true";
    }
}

if ((($pe eq "true") && ($se eq "true")) || (($pe eq "false") && ($se eq "false"))){
    die "ERROR: All input aligned files need to be in the same format (single/paired end).\n\n";
}

if ($se eq "true"){
    $se_option = "-se";
}

#check input fa, gene info
my $hap = "false";
my %CHR;
if ($EIJ eq "true"){
    open(EIJ, $geneinfo) or die "ERROR: cannot find file \"$geneinfo\"\n";
    my $header = <EIJ>;
    chomp($header);
    my @EIJHEADER = split(/\t/, $header);
    my ($chrcol, $exonstartcol, $exonendcol, $strandcol, $txSt, $txEnd, $symcol);
    for(my $i=0; $i<@EIJHEADER; $i++){
        if ($EIJHEADER[$i] =~ /strand$/){
            $strandcol = $i;
        }
        if ($EIJHEADER[$i] =~ /chrom$/){
            $chrcol = $i;
        }
        if ($EIJHEADER[$i] =~ /exonStarts$/){
            $exonstartcol = $i;
        }
        if ($EIJHEADER[$i] =~ /exonEnds$/){
            $exonendcol = $i;
        }
        if ($EIJHEADER[$i] =~ /txStart$/){
            $txSt = $i;
        }
        if ($EIJHEADER[$i] =~ /txEnd$/){
            $txEnd = $i;
        }
        if ($EIJHEADER[$i] =~ /geneSymbol$/){
            $symcol = $i;
        }
    }

    if (!defined($chrcol) || !defined($exonstartcol) || !defined($exonendcol) || !defined($strandcol) || !defined($txSt) || !defined($txEnd) || !defined($symcol)){
        die "\nERROR: Input GENE_INFO_FILE \"$geneinfo\"\nmust contain column headers with the following suffixes: chrom, strand, txStart, txEnd, exonStarts, exonEnds, and geneSymbol.\n\n";
    }
    while(my $line = <EIJ>){
        chomp($line);
        my @a = split(/\t/, $line);
        my $chr = $a[$chrcol];
        if ($chr =~ /hap/i){
            $hap = "true";
        }
        $CHR{$chr} = 1;
    }
    close(EIJ);
}
if ($GNORM eq "true"){
    open(ENS, $ensGene) or die "ERROR: cannot find file \"$ensGene\"\n";
    my $header = <ENS>;
    chomp($header);
    my @ENSHEADER = split(/\t/, $header);
    my ($txnamecol, $genenamecol, $genesymbolcol, $txchrcol, $txstartcol, $txendcol, $strandcol, $exonStcol, $exonEndcol);
    for(my $i=0; $i<@ENSHEADER; $i++){
        if ($ENSHEADER[$i] =~ /name$/){
            $txnamecol = $i;
        }
        if ($ENSHEADER[$i] =~ /name2$/){
            $genenamecol = $i;
        }
        if ($ENSHEADER[$i] =~ /strand$/){
            $strandcol = $i;
        }
        if ($ENSHEADER[$i] =~ /ensemblToGeneName.value$/){
            $genesymbolcol = $i;
        }
        if ($ENSHEADER[$i] =~ /chrom/){
            $txchrcol = $i;
        }
        if ($ENSHEADER[$i] =~ /txStart/){
            $txstartcol = $i;
        }
        if ($ENSHEADER[$i] =~ /txEnd/){
            $txendcol = $i;
        }
        if ($ENSHEADER[$i] =~ /exonStarts$/){
            $exonStcol = $i;
        }
        if ($ENSHEADER[$i] =~ /exonEnds$/){
            $exonEndcol = $i;
        }
    }
    if (!defined($genenamecol) || !defined($genesymbolcol) || !defined($txchrcol) || !defined($txstartcol)|| !defined($txendcol) || !defined($strandcol) || !defined($exonStcol) || !defined($exonEndcol)){
        die "\nERROR: Input GENE_INFO_FILE \"$ensGene\"\nmust contain column headers with the following suffixes: name, chrom, strand, txStart, txEnd, exonStarts, exonEnds, name2, ensemblToGeneName.value\n\n";
    }
    while(my $line = <ENS>){
        chomp($line);
        my @a = split(/\t/, $line);
        my $chr = $a[$txchrcol];
        if ($chr =~ /hap/i){
            $hap = "true";
        }
        $CHR{$chr} = 1;
        if ($a[$txnamecol] eq $a[$genenamecol]){
            die "\nERROR:  transcript id (name) and gene id (name2) are the same in the GENE_INFO_FILE \"$ensGene\".\n\tPORT uses the mapping of transcripts to genes Use -force_tx_gene_map flag to ";
        }
    }
    close(ENS);
}

my $hashsize0 = keys(%CHR); #all chr names in gene information file 
my $hashsize_n0 = keys(%CNAMES); #user provided chr names (if provided)
open(FA, $genome) or die "cannot open \"$genome\"\n\n";
while(my $line = <FA>){
    chomp($line);
    if ($line =~ /^>/){
        my $chr;
        if ($line =~ /\ /){
            $line =~ />(.*)/;
            my $temp = $1;
            $temp =~ s/^\s+|\s+$//g;
            my @t = split(" ", $temp);
            $chr = $t[0];
        }
        else{
            $line =~ />(.*)/;
            $chr = $1;
        }
        $chr =~ s/:[^:]*$//;
        if (exists $CHR{$chr}){
            delete $CHR{$chr};
        }
        if ($chromname eq "true"){
            if (exists $CNAMES{$chr}){
                delete $CNAMES{$chr};
            }
        }
    }
    else{
        next;
    }
}
close(FA);
# $hashsize0  #all chr names in gene information file 
# $hashsize_n0  #user provided chr names (if provided)
my $hashsize1 = keys(%CHR); 

if ($hashsize0 eq $hashsize1){ # none of chromosome names match
    die "\nERROR: Please check the input GENOME_FA \"$genome\".\nDescription line (\">\") must begin with a chromosome name that matches the chromosome names in GENE INFO (# 2. GENE INFO in your cfg file \"$cfg_file\").\nPlease check and modify the file(s) appropriately.\n\n";
}
else{
    if ($part2 eq "false"){
        if ($hashsize1 > 0){
            print STDERR "\n========\nWARNING\n========\n";
            print STDERR "The following chromosome names are in the provided GENE INFO file but not in the GENOME_FA file:\n";
            foreach my $chrom  (keys %CHR){
                print STDERR "$chrom\n";
            }
            print STDERR "\n";
        }
    }
}

if ($chromname eq "true"){
    my $hashsize_n1 = keys(%CNAMES);
    if ($hashsize_n0 eq $hashsize_n1){
        die "\nERROR: Please check the input \"$chrom\".\nNone of the chromosome names match the chromosome names in the input GENOME_FA \"$genome\".\nPlease check and modify the file(s) appropriately.\n\n";
    }
}

print SH "perl $norm_script_dir/runall_normalization.pl $argv $se_option $bam_option\n";
close(SH);

my ($p2_I, $p2_E);
if ($part2 eq "true"){
    #if -part2 is set, check to make sure runall_normalization.sh file exists.
    unless ((-e "$shdir/runall_normalization.sh") || (-e "$shdir/runall_normalization_part1_part2.sh")){
        die "ERROR: cannot find file \"$shdir/runall_normalization.sh\" or \"$shdir/runall_normalization_part1_part2.sh\".\n-part2 option cannot be used. please run the pipeline using default pipeline setting first.\n";
    }
    #if -depthE and/or -depthI is greater than before
    my $default_sh;
    if (-e "$shdir/runall_normalization.sh"){
        $default_sh = `cat $shdir/runall_normalization.sh`;
    }
    if (-e "$shdir/runall_normalization_part1_part2.sh"){
        $default_sh = `cat $shdir/runall_normalization_part1_part2.sh`;
    }
    my $part2_sh = `cat $runall_shfile`;
    my $def_E = 20;
    my $def_I = 10;
    my $res_E = 20;
    my $res_I = 10;
    if ($default_sh =~ /-depthE/){
        $default_sh =~ /-depthE\ (\d+)/;
        $def_E = $1;
        if ($def_E =~ /^$/){
            $def_E = 20;
        }
    }
    if ($default_sh =~ /-depthI/){
        $default_sh =~ /-depthI\ (\d+)/;
        $def_I = $1;
        if ($def_I =~ /^$/){
            $def_I = 10;
        }
    }
    if ($part2_sh =~ /-depthE/){
        $part2_sh =~ /-depthE\ (\d+)/;
        $p2_E = $1;
        if ($p2_E =~ /^$/){
            $p2_E = 20;
        }
    }
    else{
        $p2_E = 20;
    }
    if ($part2_sh =~ /-depthI/){
        $part2_sh =~ /-depthI\ (\d+)/;
        $p2_I = $1;
        if ($p2_I =~ /^$/){
            $p2_I = 10;
        }
    }
    else{
        $p2_I = 10;
    }
    if (($p2_E > $def_E)){
        die "ERROR: Check \"-depthE <n>\" option. <n> cannot be greater than $def_E.\n";
    }
    if (($p2_I > $def_I)){
        die "ERROR: Check \"-depthI <n>\" option. <n> cannot be greater than $def_I.\n";
    }
    #if -part2 is set and $novel is true, check and make sure study-specific master list of exon exists.
    if ($EIJ eq "true"){
        if ($novel eq "true") {
            unless (-e "$LOC/master_list_of_exons.$study.txt"){
                die "ERROR: cannot find file \"$LOC/master_list_of_exons.$study.txt\"\nMake sure PART1 completed successfully\n";
            }
        }
    }
}

sub parse_config_file () {
    my ($File, $Config) = @_;
    open(CONFIG, "$File") or die "ERROR: Config file not found : $File\n";
    while (my $config_line = <CONFIG>) {
        chomp($config_line);
        $config_line =~ s/^\s*//;
        $config_line =~ s/\s*$//;
        if ( ($config_line !~ /^#/) && ($config_line ne "") ){
            my ($Name, $Value) = split(/\s*=\s*/, $config_line,2);
            if ($Value =~ /^"/){
                $Value =~ s/^"//;
                $Value =~ s/"$//;
            }
            $Config{$Name} = $Value;
            $$Name = $Value;
        }
    }
}
sub uniq {
    my %seen;
    grep !$seen{$_}++, @_;
}
